// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@kabir.dev/cloud-auth-js";
import { supabase } from "../supabase/client";
const lovableAuth = createkabirAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const kabir = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple" | "microsoft" | "kabir", opts?: SignInOptions) => {
      const result = await kabirAuth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
